name: Itch release

on:
  release:
    types: [created, edited]
  
jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download web release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: Web.zip
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: release windows
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: HTML5
          ITCH_GAME: climbing-game
          ITCH_USER: bluebrain
          PACKAGE: web_release.zip
